[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ['python']

[[plugins]] repo = 'lambdalisue/vim-pyenv' on_ft = ['python']


[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

hook_add = '''
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_function_calls = 1
let g:go_def_mode = 'godef'
let g:go_fmt_command = "goimports"
autocmd FileType go :highlight goErr cterm=bold ctermfg=214
autocmd FileType go :match goErr /\<err\>/
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'tomlion/vim-solidity'
on_ft = ['sol']


[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md']
# hook_add = '''
# let g:vim_markdown_folding_disabled = 1
# '''

[[plugins]]
repo = 'previm/previm'
on_ft = ['md']
hook_add = '''
let g:previm_open_cmd = 'open -a Google\ Chrome'
'''

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['cpp']
hook_add = '''
let g:clang_format_auto = 1
let g:clang_format_style = 'Google'
let g:clang_check_syntax_auto = 1
'''

[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['cpp']
hook_add = '''
let g:clang_format#style_options = {
            \ "AccessModifierOffset" : -4,
            \ "AllowShortIfStatementsOnASingleLine" : "true",
            \ "AlwaysBreakTemplateDeclarations" : "true",
            \ "Standard" : "C++11",
            \ "BreakBeforeBraces" : "Stroustrup"}
'''

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['tf']
hook_add = '''
let g:terraform_align=1
let g:terraform_fmt_on_save=1
'''

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['tf']
hook_add = '''
let g:terraform_completion_keys = 1
let g:terraform_registry_module_completion = 0
'''

