[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']
hook_add = '''
let g:goimports_simplify = 1
'''

[[plugins]]
repo = 'heavenshell/vim-jsdoc'
on_ft = ['javascript', 'javascript.jsx','typescript']
build = '''
make install
'''
